name: lume_sync_server
description: Optional self-hosted sync server for Curió.
publish_to: none

environment:
  sdk: ^3.12.0

dependencies:
  crypto: ^3.0.0
  lume_core:
    path: ../packages/lume_core
